### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#12]
【目的】
ユーザが利用するシステムは、通常のWebアプリケーション形式とするため、DBスキーマの作成を行う。

【アウトプット】
ER図

【作成手順】
データ構造が正式に決定していないので、しばらくは以下のデータに関して、最小限のDBスキーマの作成を行っていく。

- 政治家の情報
- 選挙区に関する情報
  - postal2senkyoku.json
  - city2senkyoku.json

**Comment by yokinist** [comment]
候補者の画像は今回どうするんでしたっけ？

**Comment by rish314** [comment]
@ikt2y 候補者のテーブルにカラム作って、そこにimgのURLを登録する予定。ただ、GrayDBにも項目存在しません。

**Comment by rish314** [comment]
なんとなく完成したのでCLOSE
