### ISSUE TITLE
選挙区ブロックのスタイル修正

### ISSUE THREAD

**Issue by yokinist** [codeforjapan/codeforelection_front#123]
ブロックがハーマン格子になっているので負担のないようなスタイルに修正する
cf) http://uxmilk.jp/1505

**Comment by rish314** [comment]
知人から日本地図みたいなレイアウトにしたほうが良いとアドバイスを頂きましたが、如何でしょうか。

**Comment by halsk** [comment]
http://japanchoice.jp/
みたいな感じですかねー。
JapanChoice良くできてるな・・

**Comment by rish314** [comment]
> JapanChoice良くできてるな・・

同意です。今後は、独自性を出す必要がありますね。
