### ISSUE TITLE
宜しければリンク一本貼らせてください

### ISSUE THREAD

**Issue by yoshimaru7** [codeforjapan/codeforelection_front#14]
別企画で期日前投票所マップっていうの作ってまして、
「候補者ナビで出馬者の情報を見る ＞ 当日予定があっても、期日前で投票しよう」
的に連携できたら嬉しいです（単にリンク一本頂ければ可です）。

こちらでも「期日前投票に行く前に、候補の情報を確認しよう」と、候補者ナビを紹介できるので、互いにアクセスを流し合う感じに出来れば。

明日から活動始めて、全部揃うメドが13日頃、先行リリースは10日の予定です。

※なお単純なgooglemapなので、より上等なものにしれくれる人がいたらそれもウレシイ…

**Comment by halsk** [comment]
@yoshi0426 リンクをどう貼るのか教えてください

**Comment by yoshimaru7** [comment]
始めはサイトトップのどっかに…とか思ってましたが（検索ボックスだけ的なイメージだったので）予想以上に充実＆デザインも完成されているので、今から入れるのも憚られ、結果画面のフッタ「サイト運営：Code for 選挙プロジェクト」の下にちんまり「期日前投票所の場所はここから確認できます」とかはいかがでしょう？

**Comment by halsk** [comment]
貼らなかった
