### ISSUE TITLE
Facebook のリンクがエラーになる場合がある

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection_front#150]
例えば、平 将明さん
https://kouhosha.info/candidates/Q6782264
リンク先が
https://kouhosha.info/candidates/masaaki.taira.7
になってしまっている。おそらくデータの方が http://facebook.com/ から始まっていない。

**Comment by hkwi** [comment]
ちなみに、手元のデータ突き合わせ用のスクリプトでは[こんな感じ](https://github.com/hkwi/shuin48pre/blob/master/diffgen.py#L134)で処理しています。

**Comment by rish314** [comment]
model側で、httpから始まるようなValidationかけますかね。

**Comment by nyampire** [comment]
GrayDB上のデータを、http:// からはじまるURLの形に統一表記しようとしています。ちょっと時間かかると思います。それまではValidationがかかっていると嬉しいです。

**Comment by hkwi** [comment]
graydbは人間が入力するので、もうあきらめて、import 時に正規化するのが安全ですし、それがあれば統一する作業自体が不要かと。

**Comment by nyampire** [comment]
Facebook側にデータを渡すために、URLの形にする必要があるので、統一する作業が必要なのです。

**Comment by hkwi** [comment]
ですからそれは export 時点でやればよくて、gray db 上でいくら書き換えても新しいデータは入ってくるのは止められないので、そうしませんか？

**Comment by nyampire** [comment]
なるほど、意図を理解しました。GrayDB上では統一しないほうがよさそうですね。

**Comment by takahashim** [comment]
クレンジングを通したものを利用するのはいいんではないかと思います。
が、それはそれとして、ある程度統一されてないと追加で書く人がどっちを書けばいいか分からなくなるので、GrayDB上でも極力URL形式に揃えておく方がよいかと思います。

**Comment by takahashim** [comment]
ちょっとGASで一括変換できないか調べてみますね…。

**Comment by hkwi** [comment]
GAS は…すみません、今となっては重すぎるので勘弁してください。同期がどんどん重たくなっています。

**Comment by takahashim** [comment]
GASはほとんど触ったことがないんですが、1回実行するだけでも重すぎるんでしょうか？

**Comment by hkwi** [comment]
組み方にもよりますが、URL 推奨と書いておけば済む問題と考えます。

**Comment by takahashim** [comment]
そうですか、ではGASの件はいったんおいておきますね。

**Comment by nyampire** [comment]
現状のFacebookリンクに関してはURL形式に直したのでクローズ
