### ISSUE TITLE
https://kouhosha.info/download.csv が 404 エラーになる

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection_front#151]
今サーバサイドでも実行してみたところ、download.csv が出力されなくなっています。

**Comment by hkwi** [comment]
database.csv の typo ではないでしょうか。

**Comment by halsk** [comment]
あ、database.csv の typo でした。typo したのは issue 上だけなのですが、
今確認したら、
tmp/download.csv は更新出来ていることは確認できました。
以前できていた、https://kouhosha.info/download.csv が404になりますね。

**Comment by halsk** [comment]
issue のタイトル修正しました。

**Comment by halsk** [comment]
おっと、全くの僕の勘違いによる凡ミスだったようですね・・・大変失礼しました。
