### ISSUE TITLE
CSVがExcelで開けない

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#153]
Shift-JIS版も用意するか、ファイルを開く方法をガイドしたほうが良いかと思います。

**Comment by hkwi** [comment]
わはは。なるほど。export CSV には BOM マークを付けておきましょうかね。再生成するのでしばしお待ちを。

**Comment by hkwi** [comment]
普段は travis daily jobで生成しているのですが、手動で回して push しました。front サイト側での取り込みお願いします！

**Comment by halsk** [comment]
フロントサイトでは 15 分毎に graydb:import を動かしており、今見たところ database.csv も最新のものになっているみたいです。
が、database.csv をダウンロードして手元の Excel で開いたところ、文字化けしてました。

**Comment by hkwi** [comment]
現在 BOM (ef bb bf) は入っているようですね。他のかたは Excel いかがですか？

```
$ curl -s http://kouhosha.info/database.csv | od -t x1 database.csv | head -2
0000000 ef bb bf 77 69 6b 69 64 61 74 61 2c e5 90 8d e5
0000020 89 8d ef bc 88 e3 83 95 e3 83 ab ef bc 89 2c e5
```

**Comment by hkwi** [comment]
念のため xlsx 形式のファイルも出力するようにしたので、必要でしたら使ってみてください。
https://github.com/hkwi/shuin48pre/blob/master/docs/database.xlsx?raw=true

**Comment by nyampire** [comment]
対応したのでクローズ
