### ISSUE TITLE
GrayDBへの選挙結果列追加

### ISSUE THREAD

**Issue by higa4** [codeforjapan/codeforelection_front#157]
選挙結果の反映に向けてGrayDB「比例区」列の次に「比例区当選」列を追加、「小選挙区」列の次に「小選挙区当選」列と「小選挙区得票数」列を追加したいと考えていますが、Front側は問題ありませんでしょうか。

**Comment by rish314** [comment]
問題ないですよ。
ただ、当選をどういう風にフロント側で表現するかについては決まってません。
当選したかどうかを表現したほうが良いのでしょうか…。

**Comment by higa4** [comment]
了解です。それでは列を増やしますね。
当選を表現するかどうかは悩ましいですね。速報性を追うのはちょっと違う気がするので、今後どこまでやるかはじっくり検討頂いたほうがよいかもしれません。

**Comment by halsk** [comment]
済んでます
