### ISSUE TITLE
同一郵便番号で複数選挙区が存在する場合の検討

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#16]

**Comment by akiranszw** [comment]
2選挙区に分かれる郵便番号のリストです。
[devidedpostalcode.zip](https://github.com/codeforjapan/codeforelection_front/files/1375806/devidedpostalcode.zip)

**Comment by rish314** [comment]
@akiranszw ありがとうございます。58つの郵便番号が該当ですか。

**Comment by akiranszw** [comment]
ファイルの１行目は表頭なので該当する郵便番号は５７です。郵便番号は町単位なのでその中の丁目ごとに２選挙区に分割されている場合と、１つの丁目自体が分割されている場合があります。このほかに、同じ町名で大字と丁目で選挙区が異なる可能性もありますが、機械的に抽出できないので、たまたま気が付いたもの（相模原市上鶴間）だけを上げています。このケースは他にもある可能性があります。
なお、町が２選挙区に分割されている場合でも、郵便番号も分割されていれば問題ないことになります。例えば、このリストには掲載していませんが大分市廻栖野などが該当します。10月9日に私が修正したpostal2senkyoku_20171009.jsonではこのようなケースを修正してあります。

**Comment by halsk** [comment]
@rish314 これ対応しないとですね。選挙区2つ並列で出すのが良いかな

**Comment by rish314** [comment]
そもそもマスタデータとして利用している [postal2senkyoku.json](https://github.com/codeforjapan/codeforelection/blob/master/data/json/postal2senkyoku.json) に重複データとして入っていないような気がします。

さらに、土曜まで本業の出張で時間が取れないので、投票日までの対応が難しいですね…
