### ISSUE TITLE
現在地の緯度経度情報から選挙区を表示する機能の検討

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#17]

**Comment by akiranszw** [comment]
小選挙区のポリゴンデータ（座標は緯度経度）は下のURLにあります。http://www.csis.u-tokyo.ac.jp/~nishizawa/senkyoku/senkyoku289polygon_detailed_20170925.zip

**Comment by halsk** [comment]
注記をしているのでクローズ
