### ISSUE TITLE
【Question】 このフロントページレポジトリで静的ファルを共有する

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection_front#3]
こちらにファイルを挙げると、静的にダウンロードできたり共有できたりするのかな。

高木さん。郵便番号付きのデータこちらに上げられますか？
可能でしたらお願いします。

**Comment by Yuutakasan** [comment]
西沢先生の以下のデータを対象に作業をしています。

H27国勢調査町丁字と選挙区の対応表（県別のcsv形式）
http://www.csis.u-tokyo.ac.jp/~nishizawa/senkyoku/

@tetsuyas1 
現時点では以下のようにデータを整理していますが、元住所もあった方がいいとかありますか？
（重複はなくすように処理予定）

郵便番号,地方自治体コード(5桁),選挙区
064-0959,1101,北海道1区

あとデータ以下のフォーマットに合わせた方が使い勝手いいとかありますか？
http://www.popoloproject.com/specs/area.html

**Comment by tetsuyas1** [comment]
どのように使われるのかがまだ未定な部分がありますので、フォーマットはリッチな方法（必要に応じて今後減らす）でいいと思います。

私の方もマッチングが取れそうなことがわかりました。
取り急ぎ

**Comment by Yuutakasan** [comment]
@tetsuyas1 

あらら、そうなるとこっちの作業は不要ですかね？

**Comment by Yuutakasan** [comment]
@tetsuyas1 
一応、状況だけ
　大田市三瓶町（池田）池田
　石狩振興局当別町
など住所フォーマットが一般的ではないものが
引っかかっているので、全て完了にはもう少し時間がかかりそうな予感です。

**Comment by tetsuyas1** [comment]
状況ありがとうございます。
FBで書いたつもりだったのですが、こちらの作業も平行しております（が、簡便な方法でやっておりますので、可能でしたら確認したいです。）

一寸気になったので確認なのですが、東大選挙区データの住所に対して、@Yuutakasan さんお持ちのマスターの郵便番号データを当てはめた形になりますか？

KEN_ALL.csvに掲載のある郵便番号（事業所を除く）について，入力の可能性が番号について、選挙区のヒモ付が必要になるかもしれないかなと。。

取り急ぎ。

**Comment by Yuutakasan** [comment]
@tetsuyas1
了解です。
今やっているのは東大選挙区データの住所に対して、
ミーカンパニー社の郵便番号マスタをあてはめた形になります。

逆の発想で確かに郵便番号に選挙区を紐づける形で、マスタを作るのも必要そうですね。
それではこっちはKEN_ALL.csvに選挙区紐づけます。

後で双方向で確認しましょう。

**Comment by halsk** [comment]
解決という認識なので、クローズします。
