### ISSUE TITLE
404などのシステム的なページの作成依頼

### ISSUE THREAD

**Issue by chrhsmt** [codeforjapan/codeforelection_front#34]
上記、必要かと思います。
@ts020 さんなど、どなたか振り分けなどお願いいたしたく。。

**Comment by chrhsmt** [comment]
https://github.com/codeforjapan/codeforelection_front/pull/38

app/views/errors/404.html.erb
が対象ファイルです。

**Comment by chrhsmt** [comment]
郵便番号入力後に、該当選挙区が見つからない場合の遷移？をどうしましょう？
- TOPに戻してエラーメッセージ
- 選挙区ページでエラーメッセージ
- 共通のエラーページ

などなど

**Comment by halsk** [comment]
「見つかりませんでした」と出しているので終了。メニューを使ってトップに戻れる
