### ISSUE TITLE
GrayDB（GoogleSpreadSheet）からのインポート方法について

### ISSUE THREAD

**Issue by tetsuyas1** [codeforjapan/codeforelection_front#45]
# 現状の処理についての質問
15分に1回読み取るようなことをもくもく会で行ってましたが、
レポジトリのどの辺見たら詳細わかりますか？

# 実際のインポートに向けた準備について
- 相談できればと思っています。

**Comment by hkwi** [comment]
現状 google docs -> CSV というのを 15 分に一度 dump を回しています。
- リポジトリ : https://github.com/hkwi/shuin48pre/
- [CSV](https://github.com/hkwi/shuin48pre/blob/master/docs/gdoc_gray_db.csv)
- [プログラム](https://github.com/hkwi/shuin48pre/blob/master/gdoc.py)

CSV から front へは `lib/tasks/import_graydb.rake` で取り込んでいるようです。（カラム名の調整は文字列経由でやったほうがいいような…）

**Comment by rish314** [comment]
> カラム名の調整は文字列経由でやったほうがいいような…

修正しました！

**Comment by halsk** [comment]
@tetsuyas1 さん、解決しました？してたらクローズいただければ！
