### ISSUE TITLE
項目追加（前回、届け出順、比例代表、過去の当選歴）

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#57]
* 立候補したかどうか：is_candidate（boolean）true; 立候補
* 前回: current_position(integer) 0: 現職、1;新人
* 届け出順（検索結果一覧での表示順で利用）: submission_order(integer)
* 比例代表との重複: is_hirei (boolean)
* 過去の当選歴:winning_history(string) 改行区切りで当選回数を算出予定

**Comment by rish314** [comment]
* 立候補したかどうか：is_candidate（boolean）true; 立候補
* 過去の当選歴:winning_history(string) 改行区切りで当選回数を算出予定

上記はカラムを追加したが、まだ表示していない。

**Comment by yokinist** [comment]
- 小選挙区: is_syosenkyoku(boolean)
https://github.com/codeforjapan/codeforelection_front/issues/66#issuecomment-336151323
のカラム追加についてはいかがでしょうか
