### ISSUE TITLE
選挙区データ変更

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#60]
現在は軽量版（postal2senkyoku.light.json）を利用しているが、フル版（postal2senkyoku.json）を利用するように変更する。

12万件の郵便番号データを利用し、インポートに時間を要することから、インポート方法を工夫する。

**Comment by chrhsmt** [comment]
https://github.com/zdennis/activerecord-import

bulk import 使えないですかね

**Comment by rish314** [comment]
@chrhsmt 使おうと思ってます〜。今まさに着手予定！

**Comment by chrhsmt** [comment]
ただ、現状deployのタイミングでde:seedやってるので、ファイルの内容が変わって無ければskipするような処理があると嬉しいですね。ファイルのハッシュ取ってDBに入れておいて比較、とかかな。どうだろうか...

**Comment by ypresto** [comment]
oO（12万件あると歯が立たないかもしれませんが #79 でseeds.rbを高速化しました、体感でもかなり早くなったはずです）
