### ISSUE TITLE
候補者名で検索

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection_front#64]
これもあったら便利ですね

**Comment by rish314** [comment]
絶賛作業してくれる人募集中

**Comment by takahashim** [comment]
入力が漢字かな混じりで来そうなので仕様にちょっと工夫がいりそう…

**Comment by ypresto** [comment]
全文検索系のソリューションに明るくないのでアレですが・・

`田中ゆうや` → `田中` `ゆうや`
のように、漢字・かな・スペースの区切りで分割して、
```rb
    t.string "name_first", null: false
    t.string "name_last", null: false
    t.string "name_first_furigana"
    t.string "name_last_furigana"
```
のそれぞれに部分一致（または前方一致？）でAND検索かけるのはいかがでしょう？
NHK発表で1180人立候補となってるので、インデックスとか効かなくてもなんとかなるかなと思いました。

**Comment by ypresto** [comment]
あっ・・ `田中裕也` のように漢字続きの場合をどうするか・・
形態素解析的な物を使って入力された文字列を分割するか、name_fullみたいなカラムを持たせて検索する必要があるかもしれません。

**Comment by takahashim** [comment]
選挙の場合、姓だけ・名だけ平仮名にするパターンが少なからずあるため、「田中裕也」「田中ゆうや」「たなか裕也」「たなかゆうや」といったパターン全てに対応しないと使い勝手が悪そうです。
さらに、「たなか」「田中」「たなかゆう」「田中ゆ」といった、完全一致ではないパターンに対してどこまで対応するかどうか、になります。
（必要なのは前方一致のみで、部分一致・後方一致はなくても実用上問題なさそうな気がします）

**Comment by ypresto** [comment]
クエリは重くなるかもしれませんが、前述の

> `田中ゆうや` → `田中` `ゆうや`

の姓名を漢字等で区切っての検索と、 `田中裕也` `たなかゆう` をヒットさせるための `name_full` `name_full_furigana` カラムでの検索をORで同時実行すれば両方対応できる気がしてきました。
oO（前方一致だと将来的にindexが使えるのでパフォーマンス上も良さそうです・・！）

**Comment by ypresto** [comment]
GrayDBを流し見した際にはいらっしゃらないように見えましたが、ひらがなと漢字が混じる名前の人がいると、前述の漢字等の文字種で区切る方式では100%対応できないかもしれません。

**Comment by takahashim** [comment]
GrayDB内で名前に平仮名を使われている方は以下になります。

```
鎌田さゆり
円より子
松島みどり
牧島かれん
下条みつ
尾辻かな子
佐藤ゆかり
北村みき
谷川とむ
宮嶋つや子
今村あゆみ
七海ひろこ
吉田かをる
```

**Comment by ypresto** [comment]
あ、すみません名前は氏名の「名」を指していました。

> 円より子
> 尾辻かな子
> 宮嶋つや子

おおお・・・いらっしゃる・・

**Comment by ypresto** [comment]
いい感じに作れてきたのでPR送ります
