### ISSUE TITLE
GrayDB: 比例ブロックコードのカラムを追加しても問題ないでしょうか？

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection_front#66]
https://github.com/codeforjapan/codeforelection/issues/50 から来ました。

GrayDBの候補者シートには、現状比例ブロックコードのカラムがないため追加したいのですが、新しいカラムを追加してもfront側のデータインポートに支障はないでしょうか？

lib/tasks/import_graydb.rake を見る限りでは、データはカラム名から持ってきているようなので追加しても大丈夫そうですが、念のため確認です。

**Comment by rish314** [comment]
本日追加予定です。
`is_hirei` という名前でBoolean型（True/False）を追加する予定です。
Trueの場合には、GrayDBの `都道府県` 列の情報を見て、ブロックを判定する予定です。

**Comment by hkwi** [comment]
あ、比例と小選挙区両方同時にエントリしているかたもいらっしゃいます（念のため）。

**Comment by rish314** [comment]
@hkwi 

下記のように考えてます。

■小選挙区のみ出馬
　都道府県、小選挙区番号に値あり
　is_hirei: false

■小選挙区と比例
　都道府県、小選挙区番号に値あり
　is_hirei: true

■比例のみ
　都道府県に値あり
　is_hirei: true

**Comment by takahashim** [comment]
@rish314 おお、なるほど。その場合、

* GrayDBの候補者シートのどこかに`is_hirei`というカラムを追加する
* 値は `true` or `false` にする(それともGrayDB内では`0` or `1`とかにした方がよいですか？)
* `都道府県`（N列）の値は、以下のどれかの値が入る
    * 小選挙区のみの候補者の場合は都道府県コード（1〜47）
    * 比例区のみの候補者の場合は比例ブロックコード(51〜61)
    * 小選挙区・比例区両方の候補者の場合は都道府県コード（1〜47）

とするのがよいでしょうか。

**Comment by rish314** [comment]
@takahashim 

> * GrayDBの候補者シートのどこかに`is_hirei`というカラムを追加する

GrayDBのP列 `比例区` を `is_hirei` とし、に何かしらのデータが入っている場合、Trueとしてインポートする予定です。

都道府県（N列）の値は、出馬形態に関わらず、都道府県コード（1〜47）でOKです。
比例ブロックを判定する場合は、都道府県（N列）の値を見てどこのブロックか判定する予定です。

例えば、比例代表のみ（東北ブロック）の人を探す場合、 下記条件で抽出する予定です。

* is_hirei が true
* かつ都道府県コードが青森、秋田、岩手…に該当する人
* かつ小選挙区コードが空

ただ、小選挙区と同じ県の比例代表選挙にしか出馬できないというのが大前提になります。

**Comment by takahashim** [comment]
@rish314 これなんですが、特に新人とかで過去にも小選挙区に立候補したことのない、比例区のみの候補者の場合、その方の（選挙区の）都道府県がわからないこともあるんじゃないかというのを懸念しております。（それともそれはそれで情報がどこかにあるのかな？）

**Comment by rish314** [comment]
@takahashim 事務所の住所地にするという運用は難しいのでしょうか？

**Comment by takahashim** [comment]
うーん、どうなんでしょう…URLが分かってない人も多数いますし、朝日や毎日のサイトを見ても載ってなさそうです。
現実的には東北ブロックなら青森、北関東ブロックなら茨城、みたいな決め打ちで都道府県コードを振っていくのが限界そうな気がします（が、それなら比例ブロックコードのままでもいいのでは…という気持ち）。

**Comment by rish314** [comment]
@takahashim GrayDBの `比例区` にブロック名を記載下さい。以下のような仕様を考えています。

■小選挙区のみ
　都道府県、小選挙区番号に値あり
　hirei_area_no: null

■小選挙区と比例
　都道府県、小選挙区番号に値あり
　hirei_area_no: ブロックナンバー（Noはこちらで適当に採番予定）

■比例のみ
　小選挙区番号に値無し
　hirei_area_no: ブロックナンバー（Noはこちらで適当に採番予定）

**Comment by takahashim** [comment]
@rish314 `比例区`にある名前をキーにする感じにして、特に新しいカラムは追加しないということですね。了解です。

今のところ、`比例区`の値は`(北海道|東北|北関東|南関東|東京|北陸信越|東海|近畿|中国|四国|九州)`のようなパターンになっています。

**Comment by rish314** [comment]
@takahashim その認識でOKです。実装完了したら、当IssueをCLOSEします。お待ち下さい。

**Comment by yokinist** [comment]
@rish314 UI的にそれぞれ別にあったほうがわかりやすいかと思って提案です
Boolean型の `is_syosenkyoku`を新たに追加するのはいかがでしょうか

(イメージ)
[![Screenshot from Gyazo](https://gyazo.com/ca7f0c2479e82f69f44533db83065c3b/raw)](https://gyazo.com/ca7f0c2479e82f69f44533db83065c3b)

■小選挙区のみ出馬
	都道府県、小選挙区番号に値あり
	`is_syosenkyoku: true`
	`is_hirei: false`
	`hirei_area_no: null`

■小選挙区と比例
	都道府県、小選挙区番号に値あり
	`is_syosenkyoku: true`
	`is_hirei: true`
	`hirei_area_no: ブロックナンバー（Noはこちらで適当に採番予定）`

■比例のみ
        都道府県に値あり
	`is_syosenkyoku: false`
	`is_hirei: true`
	`hirei_area_no: ブロックナンバー（Noはこちらで適当に採番予定）`

**Comment by rish314** [comment]
@ikt2y やろうか！

**Comment by yokinist** [comment]
@rish314 お願いします:sob:
