### ISSUE TITLE
フロントサイトのサイト名を決める

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection_front#7]
Code for 選挙だと一般的に伝わらないので、新しい名前を考える

**Comment by halsk** [comment]
「閻魔帳」とかいかがでしょう
by @tomoaki-n

「選挙Q」QはクエリのQ とか（適当）
by @hkwi

**Comment by yokinist** [comment]
- 選Q(どこかで見覚えが・・)
- Code for Vote(語感◎)
- Vote.io(かっこいい)

**Comment by yoshimaru7** [comment]
「Code for 選挙だと一般的に伝わらない」とのことから、ひとまずCode for は外す前提ではあります。
あとハッシュタグとも共用する考えなんで、スペースやカンマもない方が…。
※短くていいんですけどね、「#Codefor選挙」。データサービスの方はそれでもいいんでは。

以下参考。既存のもので、王道（一般受け）を狙うならベタでOK）
・みんなの政治
・政治山
・選挙ドットコム
・選挙ナビ

分かりやすさで言うなら、素直に候補者って名前を付けた方が。
・候補者ナビ
・候補者バンク
・候補者図鑑
・候補者フレンズ
・候補者ンゴ
・候補一発検索
・候補ったー
・あなたの町の候補者だあれ

あとホントは「衆院選」て付けた方が分かりやすい（前後で地方選も結構あるので）んですが、ちょっと長くはなりますね…。
・衆院選候補者みえーるくん

**Comment by hkwi** [comment]
「衆院wiki」wikiとは一体…wikidata？ｗ

**Comment by tomoaki-n** [comment]
うーん…まとめると、今回の出し手としては「衆院選候補者ナビ」とかが良いんですかね。今後他の選挙でも汎用的に使っていくならその際には名前の見直しが必要ですが。

**Comment by yoshimaru7** [comment]
次回以降があるなら、メインの名前＋対応選挙名、「候補者ナビ＠2017衆院選」などでしょうか。ただ今回は冒頭から「衆院選」でいいと思います。

これまででSEO視点の議論もありましたが、検索ワードとしては確実に選挙名（衆議院選など）が入ってくるので、少なくともページタイトルとしては「衆院選〜〜」のようにした方が。

**Comment by halsk** [comment]
ベタに、衆院選候補者ナビ で行きますか
で、提供者のところに Code for 選挙プロジェクトチーム で。

**Comment by tomoaki-n** [comment]
ベタ案に賛成です。

**Comment by yokinist** [comment]
ベタだけにbetterですね

**Comment by yoshimaru7** [comment]
では #衆院選候補者ナビ 
ということで。
