### ISSUE TITLE
顔写真がほぼ無い状態なので、一旦顔写真の表示は消しておく方が良いのでは？

### ISSUE THREAD

**Issue by halsk** [codeforjapan/codeforelection_front#71]
詳細ページの顔写真のところです。みなさんどうでしょうか。

**Comment by higa4** [comment]
FBやtwitterのプロフィールページにある写真や紹介文、あるいはそれらのスクリーンショットを表示するのって、ライセンス的にはどうなんでしょう。
それが可能なら写真＞プロフィール画面　の順であるものを表示できると良さそう。
あと、写真は以下のいずれかの条件を満たすものであれば使えます。（Wikimedia commons以外ではなかなか見つかりませんが）
・政治家もしくは関係者に利用許諾を得たもの
・Wikimedia commons(ウィキペディアで使用)にあるもの
・FlickrでCreativeCommonsライセンスが適用されたもの
・Google画像検索のツール＞ライセンスで、二次利用が認められているもの
・その他、明示的に二次利用が認められているもの

**Comment by rish314** [comment]
写真ありきのデザインになっているので、無くすのも難しいと思います。

**Comment by hkwi** [comment]
EVeryPolitician は衆議院のサーバにあるものを使って、リサイズ用のプロクシ経由で動かしている？ようです。
例： http://www.shugiin.go.jp/internet/itdb_giinprof.nsf/html/profile/006.jpg/%24File/006.jpg

これがアリなのかナシなのかは私は判断が付きませんが…

**Comment by higa4** [comment]
これ、アウトですね。
http://www.shugiin.go.jp/internet/itdb_annai.nsf/html/statics/link.html
衆議院のサイトは政府標準利用規約すら適用されていない。。これはメモしといてチクるべき事案ですね ;)

**Comment by higa4** [comment]
GrayDB先頭から100件について、ウィキペディアに写真が載っているかどうかを調べてみたところ13件見つかりました。これはクレジット表記を入れれば使えます。多くはありませんが無いよりはマシなので、チェック・追記して頂ける方を募集して収集作業を進めてみます。

**Comment by ts020** [comment]
したら、画像なしパターンのレイアウト考えて見ますね。

**Comment by ts020** [comment]
顔なしにするとこんな感じになります

# 選挙区候補者リスト
![default](https://user-images.githubusercontent.com/728384/31490247-3d93847a-af7e-11e7-8d44-8611a4f5e281.png)

# 候補詳細
![default](https://user-images.githubusercontent.com/728384/31490248-3dd18efa-af7e-11e7-8e00-b6abf544b1f0.png)

**Comment by rish314** [comment]
まだ顔写真を取り込んで表示するロジックかいてませんが、どうしますか？？？

**Comment by hkwi** [comment]
（本当は選挙ポスターがいいんだろうなー）

**Comment by ts020** [comment]
後でも追加できると思うので、今は写真なしで進めて、写真が集まったらレイアウト変えましょう

**Comment by rish314** [comment]
@ts020 そうしましょう。
