### ISSUE TITLE
郵便番号から検索される選挙区が違う？

### ISSUE THREAD

**Issue by higa4** [codeforjapan/codeforelection_front#76]
FYI: 下記はまだテストできる段階ではないのかもしれませんが
http://kouhosha.info/
私の選挙区は千葉6区なのですが、自宅の郵便番号「270-2231」を入力すると千葉13区の議員が表示されます。

**Comment by chrhsmt** [comment]
light版の選挙区データのjsonに現状問題があるようです。私の住所の郵便番号「1700012」も12区なのですが、10区と表示されます。
#60 にて対応中かと思います。

**Comment by rish314** [comment]
json切り替えました。教えて頂いた郵便番号で正しい選挙区が出ることを確認済みです。
