### ISSUE TITLE
アーキテクチャの決定

### ISSUE THREAD

**Issue by rish314** [codeforjapan/codeforelection_front#8]
ユーザ向けサイトのアーキテクチャを決定する。

1. 高負荷に耐えられるような構成にする。Static Page Generatorを利用した静的なサイト生成を主とする。CDNの活用も検討する。
1. 郵便番号から選挙区の検索については、WebAPI＋Javascriptで行う。

**Comment by rish314** [comment]
「1.」については、通常のWebアプリでも、キャッシュを効かせれば高負荷に耐えられると考えています。

**Comment by rish314** [comment]
Ruby on Railsなら慣れているので、APIの作成から静的サイト作成まで出来ます。
他の言語でも、出来ないことはないです。

**Comment by chrhsmt** [comment]
>Static Page Generatorを利用した静的なサイト生成を主とする

確認したいのですが、ここで言ってる静的サイトとは、例えばJekyllなどのようなものでHTMLをファイルでそのまま生成する、という意味合いで良かったでしょうか？

**Comment by halsk** [comment]
@chrhsmt 
> 確認したいのですが、ここで言ってる静的サイトとは、例えばJekyllなどのようなものでHTMLをファイルでそのまま生成する、という意味合いで良かったでしょうか？

昨日の議論ではそういう結論だったかと思います。が、無理にそこにこだわらなくてもまずは手を動かすみなさんがやりやすい方法から始めれば良いかなとも思います。

@rish314 Ruby on Rails でキャッシュを有効化するということですね。それでも良い気もします。
@chrhsmt さんはどんなアーキテクチャだと開発しやすいですか？

**Comment by ts020** [comment]
@rish314 調べてる最中ではありますが、railsがやりやすいのであればそれで進めちゃったほうが良いと思います。
後々ボトルネックが出て来たら、ページ生成の部分を分離すればいいので、Jekyllなどと検索APIのシステム２本立てよりは初期はスムーズに進むかと

**Comment by rish314** [comment]
> 静的サイトとは、例えばJekyllなどのようなものでHTMLをファイルでそのまま生成する

静的サイトについては、その通りです。Jekyll等を利用し、CSV等からHTMLを想定しています。

ただ、私はこの案には懐疑的です。郵便番号から選挙区を検索するためにWebAPIを立てるのに、一方では、高負荷対策の為にStatic Page Generatorを利用するのは、あまり合理的ではないような気がします。

よって、アーキテクチャの方向性としては、一般的なWebアプリ形式（LAMP等）か、WebAPI＋SPAのどちらかになると思います。

**Comment by ts020** [comment]
そういう話であれば、SEOの観点もあるので素直なwebアプリ形式でCNDキャッシュを利かすというのでいいと思います。

**Comment by ts020** [comment]
そしたら、テンプレートエンジンslimってあんまり慣れてなくてできれば何ですがこっち使えますか？
https://github.com/paulrex/jade-rails

**Comment by rish314** [comment]
素直なWebアプリであれば、PHPでもRailsでも構いませんが、特に意見が無ければ、Ruby on Railsで作成させて頂こうかなと思います。
本当は技術的なチャレンジがしたいですが、納期優先で慣れた方式にさせて頂きます。今週金曜日までにプロトタイプをアップします。

**Comment by rish314** [comment]
jadeでも使えると思いますよ。hamlやslimの競合ですよね。

**Comment by rish314** [comment]
@ts020 HTMLとJavascriptのフレームワークの希望あります？　私は、いつもはjQueryとTwitter BootStrapですが…そろそろ別のものにチャレンジしたい気持ちもありつつ、短納期だしなぁといったところです。

https://semantic-ui.com
とか気になります。

**Comment by ts020** [comment]
@rish314 jadeはその通りテンプレートエンジンです。
フロントのフレームワークですが、使うのであればVue.jsをここ３年くらい使ってます。
cssに関してはjsで扱いにくかったり、スタイルの調整がやりにくいシーンが結構あったりするのでフレームワークは使わず生でsassかpost-cssで書いて、autoPrifixerを通してベンダープリフィクス付けてる感じです。

**Comment by rish314** [comment]
@ts020 
Vue.jsいいですね。いま、個人的に勉強**着手中**です。

cssだけのフレームワークは不要だと思いますが、Twitter BootStrap等のHTMLフレームワークが無いと、カラムレイアウトやレスポンシブ対応が面倒なイメージがあるのですが、こちらは何も使わない想定でしょうか？

**Comment by ts020** [comment]
@rish314 
bootstap等は何も使わないイメージです。
むしろフレームワークに振り回されていい印象がないです。
スクラッチでのレスポシンブも特に問題ないです。

**Comment by rish314** [comment]
以下の構成を考えています。その他意見等ございませんでしょうか。

- OS
  -  Ubuntu@さくらVPS
- Webサーバ
  -  Apache Passenger
- DB
  -  MySQL
- アプリケーション
  -  Ruby on Rails
- ビュー
  - jade（テンプレートエンジン）、Vue.js（Javscriptフレームワーク）、post-css（スタイルシート）

**Comment by chrhsmt** [comment]
railsで問題ないと思います。時間が短いこともありますし。

Vue.jsは僕はあまり使用経験が無いので調査しながら作業という形で対応になりますが、1つ疑問点がありまして、今回はSEOの考慮があるとのことでしたので、jsによるhtmlのレンダリングは行わないのかなと思っていましたがどうなのでしょうか？(Vue.jsに詳しくないので質問をしました)

**Comment by ts020** [comment]
@chrhsmt Vue.jsですが利用シーンとしては、検索UIなど、SEOに関わらないUI部品レベルのものをjsからHTMLレンダリングするという位の想定なのでほぼ触らないと思ってもらって大丈夫です。
今回vueはあとで色気出すとき以外は出番なさそうです。

**Comment by ts020** [comment]
@rish314 特に問題ないです

**Comment by chrhsmt** [comment]
@ts020 了解いたしました。ありがとうございます。

**Comment by ts020** [comment]
@rish314 すみません、post-cssのmoduleで、postcss-cssnextを使いたいのでアーキテクチャに追加しておいてもらえるとありがたいです。
あと、今回の場合だと、タスクランナーにgulpを使うと思います。

**Comment by chrhsmt** [comment]
https://github.com/rails/webpacker

railsと組み合わせるなら、webpackerを使うのもありかな、と思いましたが、post-cssと上手く連動できるのか試したことがないですね。どうでしょうか(混乱させてしまったらすみません)

**Comment by rish314** [comment]
一旦、細かいところは置いておいて、先に進みたいと思います。
docker-composeでraiils環境構築中です。

**Comment by ts020** [comment]
@rish314 はいよろしくお願いします。
@chrhsmt 確かに普段はwebpack使ってるんですが、今回の場合ビルドが必要なのはcssだけですので、webpackの謎設定を描くのは割りに合わないと思いましたので、あえてのgulp提示といった塩梅です。

**Comment by rish314** [comment]
土用の午後にはいったんコミットします。

**Comment by yokinist** [comment]
@ts020 候補者リストアイテムのレイアウトやSP対応を考えるとTwitter BootStrapのGrid systemだけでもいれてもいいかなと思いますがいかがでしょうか

**Comment by rish314** [comment]
なんとなく落ち着いたのでCLOSE
