### ISSUE TITLE
「森山𥙿」がインポートできない

### ISSUE THREAD

**Issue by takahashim** [codeforjapan/codeforelection_front#80]
森山𥙿氏の「𥙿」は「しめす偏に谷」だそうです。
https://ja.wikipedia.org/wiki/%E6%A3%AE%E5%B1%B1%E8%A3%95

これはUnicodeではU+2567Fで、BMPの範囲外になり、サロゲートペアでなければ表示できません。
http://glyphwiki.org/wiki/u2567f
http://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2567f

そのため、MySQLに投入する時点でエラーになっているようです。

```
$ bundle exec rake graydb:import
["UI用DBカラム名", "name_full", "name_last", "name_first", "name_alias", "name_full_furigana", "pary_id", nil, "party_history", "is_candidate", "current_position", "submission_order", nil, "pref_code", "senkyoku_no", "hirei_area_id", nil, "candidacy_history", "winning_history", "gender", "birth_day", nil, "birth_year", "photo_url", "twitter_id", "facebook_id", "facebook_page_id", "line_id", "youtube_channel_id", "instagram_id", "offiicial_website_url", "email", "official_blog_url", "reference_url", "birth_place", "educational_background", nil, "occupation", "position_held", "father", "spouse", nil, "url_wikidata", "url_wikipedia", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]

Mysql2::Error: Incorrect string value: '\xF0\xA5\x99\xBF' for column 'name_first' at row 1: INSERT INTO `candidates` (`name_first`, `name_last`, `name_first_furigana`, `name_last_furigana`, `party_id`, `gender`, `birth_day`, `birth_year`, `official_website_url`, `created_at`, `updated_at`, `wikidata_id`, `is_candidate`, `current_position`, `winning_history`, `hirei_area_id`) VALUES ('𥙿', '森山', 'ひろし', 'もりやま', 12, 1, '1945-04-08', 1945, 'http://www.moriyama-hiroshi.jp/', '2017-10-12 14:45:44', '2017-10-12 14:45:44', 'Q337762', 1, 1, '1975年鹿児島市議会議員補欠選挙\n第18回参議院議員通常選挙\n2004年衆議院鹿児島5区補欠選挙\n第44回衆議院議員総選挙\n第45回衆議院議員総選挙\n第46回衆議院議員総選挙\n第47回衆議院議員総選挙', 11)
#<ActiveModel::Errors:0x007fb2ba350c68 @base=#<Candidate id: nil, name_first: "𥙿", name_last: "森山", name_first_furigana: "ひろし", name_last_furigana: "もりやま", party_id: 12, senkyoku_id: nil, gender: 1, birth_day: "1945-04-08", birth_year: 1945, twitter_id: nil, facebook_id: nil, official_website_url: "http://www.moriyama-hiroshi.jp/", photo_url: nil, created_at: "2017-10-12 14:45:44", updated_at: "2017-10-12 14:45:44", wikidata_id: "Q337762", is_candidate: true, current_position: 1, submission_order: nil, winning_history: "1975年鹿児島市議会議員補欠選挙\n第18回参議院議員通常選挙\n2004年衆議院鹿児島5区補欠選挙\n...", hirei_area_id: 11>, @messages={}, @details={}>
```

## 解決策

1. MySQLの文字コードを`utf8`から`utf8mb4`にすればよい？（で、あってます？ MySQLはあんまり詳しくないので…）
2. 「裕」(U+88D5)にする
3. 「ひろし」にする

1で解決できそうなら1が良いと思いますが、どうなんでしょう？

**Comment by hkwi** [comment]
そうなんですよね。異字体まわりは、どこかのタイミングで手を付けないとなとは思ってはいますが、なにぶん機械処理しにくい領域なので悩みます。

ちなみに codeforjapan/codeforelection#29 の通り、当選した暁には議事録 API で引けるようになるはずなので、そんなに難しくない代表的な表現への変換規則が定まっているはず……（なのでその照会表が欲しい…）

**Comment by ypresto** [comment]
該当APIでは `(※3)UTF-8で送信されたリクエストは内部的にEUCに変換されます。` との記載があります。
`森山𥙿` は直接EUCに変換できないですが、speakerで引くと `森山裕` に変換されたエントリがヒットします。

http://kokkai.ndl.go.jp/api/1.0/speech?startRecord%3D1%26maximumRecords%3D5%26any%3D%E3%82%A2%E3%83%99%E3%83%8E%E3%83%9F%E3%82%AF%E3%82%B9%26speaker%3D%E6%A3%AE%E5%B1%B1%F0%A5%99%BF
↑
http://kokkai.ndl.go.jp/api/1.0/speech?startRecord%3D1%26maximumRecords%3D5%26any%3Dアベノミクス%26speaker%3D森山𥙿

**Comment by ypresto** [comment]
変換テーブルの所在は不明です・・ｗ

**Comment by hkwi** [comment]
もういっそAPIを変換コーデックとして使うか…。API は解釈済みのクエリパラメータをオウム返ししてくれないんですね。収録されている分だけでも変換してみるか。

**Comment by rish314** [comment]
MySQLの文字コードを `utf8` から `utf8mb4` にしたら取り込みできました。詳しいことは分かりませんが、MySQLの文字コードを変更することは可能です。

![___kouhosha_info](https://user-images.githubusercontent.com/446201/31531367-b89c8966-b021-11e7-95d5-b828d3a82f56.png)

**Comment by hkwi** [comment]
それが一番いい対応方法ですね ^^

**Comment by takahashim** [comment]
コードベースでは対応済みで、本番サーバの更新待ちです

**Comment by halsk** [comment]
解決しました。失礼しました。

**Comment by takahashim** [comment]
確認できました、ありがとうございました！

**Comment by rish314** [comment]
こちらも確認しました！　ありがとうございました！
